name: Build+Test+Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      # no tests yet
      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build-storybook

      - name: Build
        run: npm run build

      - name: include storybook to dist
        run: cp -r ./storybook-static ./dist/storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
